project_name: access-controller

before:
  hooks:
    - make generate
builds:
  - main: ./cmd/access-controller/main.go
    binary: bin/access-controller
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - darwin
dockers:
  -
    image_templates:
    - "gcr.io/authorizer-tech/access-controller:latest"
    - "gcr.io/authorizer-tech/access-controller:{{ .Tag }}"
    - "gcr.io/authorizer-tech/access-controller:v{{ .Major }}"
    - "gcr.io/authorizer-tech/access-controller:v{{ .Major }}.{{ .Minor }}"
    extra_files:
    - testdata
    - db/migrations
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
