apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "access-controller.fullname" . }}-config
  labels:
    {{- include "access-controller.labels" . | nindent 4 }}
data:
  config.yaml: |
    grpcGateway:
      enabled: {{ .Values.grpcGateway.enabled }}
    postgres:
      host: {{ .Values.postgres.host }}
      port: {{ .Values.postgres.port }}
      database: {{ .Values.postgres.database }}
