name: post-merge

on:
  push:
    branches:
      - master

jobs:
  code-coverage:
    name: Update Go Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - run: echo $(go env GOPATH)/bin >> $GITHUB_PATH

      - name: "Go: Test Coverage"
        run: |
          make generate ci-test-coverage

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)